In [14]:
from Princess import Princess_Syndrome

In [15]:
arg = {
    'characteristic': ["A","B","C"], # 工具人有幾項工作要做
    'peoples' : ["0","1","2","3"], # 手上有幾個工具人(必須是0-n)
    'costs' : {
        'A':[2,2,2,2], # 從0-3號工具人 做Ａ工作所需要的cost
        'B':[0,99,99,5], # 從0-3號工具人 做B工作所需要的cost
        'C':[1,2,1,5] # 從0-3號工具人 做C工作所需要的cost
    },
    'quality' : {
        'A':[1,2,3,5], # 從0-3號工具人 做Ａ工作所做的品質（可以想成工具人寫作業，每個工具人寫出來的分數不一樣）
        'B':[4,5,6,5], # 從0-3號工具人 做B工作所做的品質
        'C':[7,8,9,5] # 從0-3號工具人 做C工作所做的品質
    },
    'demand' : {
        'A':2, #A工作最低需要的品質 可以想成你希望工具人幫你寫作業，但至少寫出來要60分吧？
        'B':5, #B工作最低需要的品質
        'C':7  #C工作最低需要的品質
    },
}

Princess = Princess_Syndrome(arg)
result = Princess.solve()
Princess.print_result()

Status: Optimal


0    1    2    3
A  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0

In [16]:
Princess.loss() #總成本

8.0

In [1]:
import numpy as np

In [10]:
def gen_data(mean,num,std = 5):
    return np.random.normal(mean, std, num)

num = 5
array = [60,75,90,80,85]
for e in array:
    print(gen_data(e,num))

[ 62.67577832  50.45988989  59.81968637  58.23464468  58.74522314]
[ 78.27795615  80.19177331  73.22139319  74.48580965  79.14250144]
[ 94.9171405   95.43180825  83.7914595   84.9505391   79.47272129]
[ 77.30087707  66.97801586  76.75618065  82.1177153   75.72382989]
[ 88.8414469   82.29058764  81.01579826  76.26119109  86.40903681]


In [11]:
num = 5
array = [60,75,90,80,85]
for e in array:
    print(gen_data(e,num))

[ 65.92627389  53.68144095  54.8428643   57.88961829  53.97201671]
[ 82.27187517  72.2773425   68.36013685  70.82068056  73.216982  ]
[ 86.33735506  85.47554073  94.86559769  85.85512828  90.80384008]
[ 81.82848358  84.81851669  81.56259151  82.25083047  83.37700525]
[ 78.66909659  92.40899159  85.6629489   82.70513902  81.56786418]


In [1]:
from Princess import Princess_Syndrome 
from numpy import random

def new_cost(arg,table):
    mean = {}
    for char in arg['costs']:
        mean[char] = 0;
        num = 0
        for person in arg['costs'][char]:
            num+=1
            mean[char]+=person
        mean[char]/=num
    num = 0
    for char in arg['costs']:
        for person in range(0,len(arg['costs'][char])):
            if table.values[num][person] == 1:
                arg['costs'][char][person] *= 1.02
            else:
                arg['costs'][char][person] *= 0.98
            arg['costs'][char][person] = int(arg['costs'][char][person])+1
        num+=1
    return arg;

arg = {
    'characteristic': ["作業","接送","情緒垃圾桶","陪吃飯","修3C"], # 工具人有幾項工作要做
    'peoples' : ["0","1","2","3","4"], # 手上有幾個工具人(必須是0-n)
    'costs' : {
        '作業':[62.67577832,50.45988989 , 59.81968637 , 58.23464468 , 58.74522314], # 從0-3號工具人 做Ａ工作所需要的cost
        '接送':[ 78.27795615 ,80.19177331 , 73.22139319 , 74.48580965 , 79.14250144], # 從0-3號工具人 做B工作所需要的cost
        '情緒垃圾桶':[ 94.9171405,95.43180825 , 83.7914595  , 84.9505391  , 79.47272129],
        '陪吃飯':[ 77.30087707 ,66.97801586  ,76.75618065 , 82.1177153  , 75.72382989],
        '修3C':[ 88.8414469  , 82.29058764 , 81.01579826  ,76.26119109 , 86.40903681]# 從0-3號工具人 做C工作所需要的cost
    },
    'quality' : {
        '作業':[0 for i in range(5)], # 從0-3號工具人 做Ａ工作所做的品質（可以想成工具人寫作業，每個工具人寫出來的分數不一樣）
        '接送':[0 for i in range(5)], # 從0-3號工具人 做B工作所做的品質
        '情緒垃圾桶':[0 for i in range(5)],
        '陪吃飯':[0 for i in range(5)],
        '修3C':[0 for i in range(5)] # 從0-3號工具人 做C工作所做的品質
    },
    'demand' : {
        '作業':0, #A工作最低需要的品質 可以想成你希望工具人幫你寫作業，但至少寫出來要60分吧？
        '接送':0, #B工作最低需要的品質
        '情緒垃圾桶':0,
        '陪吃飯':0,
        '修3C':0#C工作最低需要的品質
    },
}
arg = {
    'characteristic': ["A","B","C","D","E"], # 工具人有幾項工作要做
    'peoples' : ["0","1","2","3","4"], # 手上有幾個工具人(必須是0-n)
    'costs' : {
        'A':[62.67577832,50.45988989 , 59.81968637 , 58.23464468 , 58.74522314], # 從0-3號工具人 做Ａ工作所需要的cost
        'B':[ 78.27795615 ,80.19177331 , 73.22139319 , 74.48580965 , 79.14250144], # 從0-3號工具人 做B工作所需要的cost
        'C':[ 94.9171405,95.43180825 , 83.7914595  , 84.9505391  , 79.47272129],
        'D':[ 77.30087707 ,66.97801586  ,76.75618065 , 82.1177153  , 75.72382989],
        'E':[ 88.8414469  , 82.29058764 , 81.01579826  ,76.26119109 , 86.40903681]# 從0-3號工具人 做C工作所需要的cost
    },
    'quality' : {
        'A':[0 for i in range(5)], # 從0-3號工具人 做Ａ工作所做的品質（可以想成工具人寫作業，每個工具人寫出來的分數不一樣）
        'B':[0 for i in range(5)], # 從0-3號工具人 做B工作所做的品質
        'C':[0 for i in range(5)],
        'D':[0 for i in range(5)],
        'E':[0 for i in range(5)] # 從0-3號工具人 做C工作所做的品質
    },
    'demand' : {
        'A':0, #A工作最低需要的品質 可以想成你希望工具人幫你寫作業，但至少寫出來要60分吧？
        'B':0, #B工作最低需要的品質
        'C':0,
        'D':0,
        'E':0#C工作最低需要的品質
    },
}

In [2]:
for i in range(100):
    princess = Princess_Syndrome(arg)
    result = princess.solve()
    table = princess.get_table()
    arg = new_cost(arg,table)
    princess.print_result()

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  0.0  1.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  0.0  1.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  1.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  1.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  1.0  0.0  0.0  0.0  0.0
D  0.0  0.0  0.0  0.0  1.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  0.0  1.0
B  1.0  0.0  0.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  1.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

Status: Optimal


0    1    2    3    4
A  0.0  1.0  0.0  0.0  0.0
B  0.0  0.0  1.0  0.0  0.0
C  0.0  0.0  0.0  1.0  0.0
D  1.0  0.0  0.0  0.0  0.0
E  0.0  0.0  0.0  0.0  1.0

Status: Optimal


0    1    2    3    4
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  0.0  0.0  1.0
D  0.0  0.0  1.0  0.0  0.0
E  0.0  0.0  0.0  1.0  0.0

In [7]:
import pprint

In [3]:
arg

{'characteristic': ['A', 'B', 'C', 'D', 'E'],
 'costs': {'A': [52, 51, 50, 50, 50],
  'B': [50, 52, 51, 50, 50],
  'C': [50, 50, 50, 51, 52],
  'D': [51, 50, 52, 50, 50],
  'E': [50, 50, 50, 52, 51]},
 'demand': {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0},
 'peoples': ['0', '1', '2', '3', '4'],
 'quality': {'A': [0, 0, 0, 0, 0],
  'B': [0, 0, 0, 0, 0],
  'C': [0, 0, 0, 0, 0],
  'D': [0, 0, 0, 0, 0],
  'E': [0, 0, 0, 0, 0]}}

In [4]:
princess = Princess_Syndrome(arg)
result = princess.solve()
table = princess.get_table()
arg = new_cost(arg,table)
princess.print_result()

Status: Optimal


0    1    2    3    4
A  0.0  0.0  0.0  1.0  0.0
B  0.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  1.0  0.0  0.0  0.0
E  1.0  0.0  0.0  0.0  0.0

In [5]:
arg

{'characteristic': ['A', 'B', 'C', 'D', 'E'],
 'costs': {'A': [51, 50, 50, 52, 50],
  'B': [50, 51, 50, 50, 52],
  'C': [50, 50, 52, 50, 51],
  'D': [50, 52, 51, 50, 50],
  'E': [52, 50, 50, 51, 50]},
 'demand': {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0},
 'peoples': ['0', '1', '2', '3', '4'],
 'quality': {'A': [0, 0, 0, 0, 0],
  'B': [0, 0, 0, 0, 0],
  'C': [0, 0, 0, 0, 0],
  'D': [0, 0, 0, 0, 0],
  'E': [0, 0, 0, 0, 0]}}

In [9]:
pow(1.02,100)

7.244646118252348