In [1]:
from Princess import Princess_Syndrome

In [4]:
arg = {
    'characteristic': ["A","B","C"], # 工具人有幾項工作要做
    'peoples' : ["0","1","2","3"], # 手上有幾個工具人(必須是0-n)
    'costs' : {
        'A':[2,4,5,5], # 從0-3號工具人 做Ａ工作所需要的cost
        'B':[0,99,99,5], # 從0-3號工具人 做B工作所需要的cost
        'C':[1,2,1,5] # 從0-3號工具人 做C工作所需要的cost
    },
    'quality' : {
        'A':[1,2,3,5], # 從0-3號工具人 做Ａ工作所做的品質（可以想成工具人寫作業，每個工具人寫出來的分數不一樣）
        'B':[4,5,6,5], # 從0-3號工具人 做B工作所做的品質
        'C':[7,8,9,5] # 從0-3號工具人 做C工作所做的品質
    },
    'demand' : {
        'A':2, #A工作最低需要的品質 可以想成你希望工具人幫你寫作業，但至少寫出來要60分吧？
        'B':5, #B工作最低需要的品質
        'C':7  #C工作最低需要的品質
    },
}

Princess = Princess_Syndrome(arg)
result = Princess.solve()
Princess.print_result()

Status: Optimal


0    1    2    3
A  0.0  1.0  0.0  0.0
B  0.0  0.0  0.0  1.0
C  1.0  0.0  0.0  0.0

In [3]:
Princess.loss() #總成本

10.0

In [1]:
import numpy as np

In [10]:
def gen_data(mean,num,std = 5):
    return np.random.normal(mean, std, num)

num = 5
array = [60,75,90,80,85]
for e in array:
    print(gen_data(e,num))

[ 62.67577832  50.45988989  59.81968637  58.23464468  58.74522314]
[ 78.27795615  80.19177331  73.22139319  74.48580965  79.14250144]
[ 94.9171405   95.43180825  83.7914595   84.9505391   79.47272129]
[ 77.30087707  66.97801586  76.75618065  82.1177153   75.72382989]
[ 88.8414469   82.29058764  81.01579826  76.26119109  86.40903681]


In [11]:
num = 5
array = [60,75,90,80,85]
for e in array:
    print(gen_data(e,num))

[ 65.92627389  53.68144095  54.8428643   57.88961829  53.97201671]
[ 82.27187517  72.2773425   68.36013685  70.82068056  73.216982  ]
[ 86.33735506  85.47554073  94.86559769  85.85512828  90.80384008]
[ 81.82848358  84.81851669  81.56259151  82.25083047  83.37700525]
[ 78.66909659  92.40899159  85.6629489   82.70513902  81.56786418]
